#! /usr/bin/env python

###############################################################################
#
#
# Package:   RoadNarrows Robotics ROS Pan-Tilt Robot Package
#
# Link:      https://github.com/roadnarrows-robotics/pan_tilt
#
# ROS Node:  pan_tilt_panel
#
# File:      pan_tilt_panel.cpp
#
## \file 
##
## $LastChangedDate$
## $Rev$
##
## \brief Graphical panel interface with the pan_tilt_control node.
##
## \author Daniel Packard (daniel@roadnarrows.com)
## \author Robin Knight (robin.knight@roadnarrows.com)
##  
## \par Copyright:
##   (C) 2014.  RoadNarrows LLC.\n
##   (http://www.roadnarrows.com)\n
##   All Rights Reserved
##
# @EulaBegin@
# @EulaEnd@
#
###############################################################################

import sys
import os
import time
import math
import getopt

from Tkinter import *
from Tkconstants import *
from tkFileDialog import *
import tkFont

from PIL import Image, ImageTk

import webbrowser
import xml.parsers.expat as expat

import roslib; roslib.load_manifest('pan_tilt_control')
import rospy

import actionlib
from actionlib_msgs.msg import GoalStatus
import trajectory_msgs.msg

from industrial_msgs.msg import RobotMode
from industrial_msgs.msg import TriState

from pan_tilt_control.msg import RobotStatusExtended
from pan_tilt_control.msg import JointStateExtended
from pan_tilt_control.msg import ServoHealth
from pan_tilt_control.msg import OpState
from pan_tilt_control.msg import ProductInfo

from pan_tilt_control.srv import GotoZeroPt
from pan_tilt_control.srv import EStop
from pan_tilt_control.srv import ResetEStop
from pan_tilt_control.srv import Freeze
from pan_tilt_control.srv import Release
from pan_tilt_control.srv import ClearAlarms
from pan_tilt_control.srv import GetProductInfo

#import pan_tilt_control.msg

from pan_tilt_control.ACCalibrate import *
from pan_tilt_control.AboutDlg import AboutDlg


# ------------------------------------------------------------------------------
# Globals
# ------------------------------------------------------------------------------

## \brief Application version. Update as needed. 
appVersion = '1.0.0'

## \brief Image search paths.
imagePath = [
  "/prj/pkg/Hekateros/share/images",
  "/usr/local/share/Hekateros/images",
  "/prj/pkg/appkit/share/images",
  "/usr/local/share/appkit/images"
]

## \brief User's home directory.
home = os.path.expanduser("~")

## \brief Pan-tilt user-specific configuration directory (in home directory).
pantiltUserDirName = ".roadnarrows"

## \brief pan_tilt_panel application configuration file name.
configFileName = "pan_tilt_panel.xml"

## \brief Configuration default.
configDft = \
{
  'warn_on_calib':    True, # do [not] warn user at calibration start
  'warn_on_release':  True, # do [not] warn user on release
  'force_recalib':    True, # do [not] force recalibration on all joints
}

## \brief Alarm strings.
alarmStrings = {
  ServoHealth.ALARM_NONE:         "ok",
  ServoHealth.ALARM_VOLTAGE:      "V",
  ServoHealth.ALARM_ANGLE:        "pos",
  ServoHealth.ALARM_TEMP:         "T",
  ServoHealth.ALARM_CMD_RANGE:    "",
  ServoHealth.ALARM_CHECKSUM:     "",
  ServoHealth.ALARM_LOAD:         "load",
  ServoHealth.ALARM_INSTRUCTION:  ""
}

## \brief Common foreground colors.
fgColors = {
  'normal':   'black',
  'ok':       '#008800',
  'focus':    '#0000aa',
  'warning':  '#aa6600',
  'error':    '#cc0000'
}


# ------------------------------------------------------------------------------
# Utilities
# ------------------------------------------------------------------------------

#
## \brief Load icon image from file name.
##
## \param filename    Icon file name.
##
## \return Returns icon widget on success, None on failure.
#
def loadIcon(filename):
  # no file name
  if filename is None or len(filename) == 0:
    return None;
  # absolute file name
  if filename[0] == os.path.sep:
    try:
      return ImageTk.PhotoImage(Image.open(filename))
    except IOError:
      return None
  # relative file name - search path for file
  for path in imagePath:
    fqname = path + os.path.sep + filename
    try:
      return ImageTk.PhotoImage(Image.open(fqname))
    except IOError:
      continue
  return None

#
## Round to nearest 100th.
#
def round100th(x):
  return math.floor((x + 0.005) * 100.0) / 100.0

#
## Round to nearest 10th.
#
def round10th(x):
  return math.floor((x + 0.05) * 10.0) / 10.0

#
## Degrees to radians.
#
def degToRad(deg):
  return deg / 180.0 * math.pi

#
## Radians to degrees.
#
def radToDeg(rad):
  return rad / math.pi * 180.0


# ------------------------------------------------------------------------------
# Class configXml
# ------------------------------------------------------------------------------

##
## \brief Application pan_tilt_panel configuration xml class.
##
class configXml():
  def __init__(self):
    self.m_inRootElem   = False
    self.m_inMainElem   = False
    self.m_curCfgElem   = None
    self.m_curData      = ""
    self.m_cfgElems     = configDft.keys()
    self.m_config       = None

  def parse(self, pathname):
    self.m_config = configDft
    try:
      fp = open(pathname, 'r')
    except IOError, err:
      return self.m_config
    parser = expat.ParserCreate()
    parser.returns_unicode      = False
    parser.StartElementHandler  = self.onElemStart
    parser.CharacterDataHandler = self.onElemData
    parser.EndElementHandler    = self.onElemEnd
    try:
      parser.ParseFile(fp)
    except expat.ExpatError as e:
      print "%s: %s" % (pathname, expat.ErrorString(e.code))
    fp.close()
    return self.m_config

  def save(self, pathname, config):
    try:
      fp = open(pathname, 'w')
    except IOError, err:
      print "%s: %s." % (pathname, err)
      return
    fp.write("""\
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="http://roadnarrows.com/xml/PanTilt/1.0/pan_tilt.xsl"?>

<!-- RoadNarrows Pan-Tilt Top-Level Configuration -->
<pantilt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://roadnarrows.com/xml/PanTilt/1.0/pan_tilt.xsd">

  <!-- pan_tilt_panel configuration -->
  <pan_tilt_panel>
""")

    for key in self.m_cfgElems:
      fp.write("    <%s>%d</%s>\n" % (key, config[key], key))

    fp.write("""\
  </pan_tilt_panel>

</pantilt>
""")

    fp.close()

  def onElemStart(self, elem, attrs):
    #print "start-of-element", "<%s> attrs=%s" % (elem, repr(attrs))
    if elem == 'pantilt':
      self.m_inRootElem = True
    elif elem == 'pan_tilt_panel':
      if self.m_inRootElem:
        self.m_inMainElem = True
      else:
        self.m_inMainElem = False
    elif elem in self.m_cfgElems:
      if self.m_inMainElem:
        self.m_curCfgElem = elem
      else:
        self.m_inMainElem = None
    self.m_curData  = ""

  def onElemData(self, data):
    #print "char-data", repr(data)
    self.m_curData += data

  def onElemEnd(self, elem):
    #print "end-of-element", "<\%s>" % (elem)
    if self.m_curCfgElem:
      self.cvtToBool(self.m_curCfgElem, self.m_curData.strip())
    if elem == 'pan_tilt_panel':
      self.m_inMainElem = False
    elif elem == 'pantilt':
      self.m_inRootElem = False
      self.m_inMainElem = False
    m_curCfgElem = None
    self.m_curData  = ""

  def cvtToBool(self, elem, data):
    if data.lower() == 'true':
      self.m_config[elem] = True
    elif data.lower() == 'false':
      self.m_config[elem] = False
    else:
      try:
        i = int(data)
      except ValueError:
        return
      if i:
        self.m_config[elem] = True
      else:
        self.m_config[elem] = False


# ------------------------------------------------------------------------------
# Class configDlg
# ------------------------------------------------------------------------------

class configDlg(Toplevel):
  #
  ## \brief Constructor.
  ##
  ## \param cnf     Configuration dictionary.
  ## \param kw      Keyword options.
  #
  def __init__(self, master=None, cnf={}, **kw):
    # initialize dialog data
    kw = self.initData(kw)

    Toplevel.__init__(self, master=master, cnf=cnf, **kw)
    self.title("pan_tilt_panel configuration")

    # create and show widgets
    self.createWidgets()

    # allows the enter button to fire either button's action
    self.m_bttnCancel.bind('<KeyPress-Return>', func=self.close)

    # center the dialog over parent panel
    if master is not None:
      self.update_idletasks()
      x0 = master.winfo_rootx()
      y0 = master.winfo_rooty()
      xp = x0 + (master.winfo_width() - self.winfo_width()) / 2 - 8
      yp = y0 + (master.winfo_height() - self.winfo_height()) / 2 - 20
      glist = [self.winfo_width(), self.winfo_height(), xp, yp]
      #self.withdraw() # hide the dialog until position and size is set
      self.geometry('{0}x{1}+{2}+{3}'.format(*glist))
      #self.deiconify() # now show

    # allows us to customize what happens when the close button is pressed
    self.protocol("WM_DELETE_WINDOW", self.close)

    #
    # Modal diagle settings.
    #
    # set the focus on dialog window (needed on Windows)
    self.focus_set()

    # make sure events only go to our dialog
    self.grab_set()

    # make sure dialog stays on top of its parent window (if needed)
    self.transient(master)

    # display the window and wait for it to close
    self.wait_window(self)

  #
  ## \brief Initialize class state data.
  ##
  ## \param kw      Keyword options.
  ##
  ## \return Modified keywords sans this specific class.
  ##
  def initData(self, kw):
    if kw.has_key('config'):
      self.m_config = kw['config']
      del kw['config']
    else:
      self.m_config = configDft;
    return kw

  #
  ## \brief Create gui widgets with supporting data and show.
  #
  def createWidgets(self):
    frame = Frame(self)
    frame.grid(row=0, column=0)

    # top heading
    w = Label(frame)
    helv = tkFont.Font(family="Helvetica",size=24,weight="bold")
    w['font']   = helv
    w['text']   = 'Configuration'
    w['anchor'] = CENTER
    w.grid(row=0, column=0, sticky=E+W)

    row = 1

    # warn on calibrate check button
    self.m_varWarnCalib = IntVar()
    self.m_varWarnCalib.set(self.m_config['warn_on_calib'])
    w = Checkbutton(frame,
        text="Show warning dialog before calibrating pan-tilt.",
        variable=self.m_varWarnCalib)
    w.grid(row=row, column=0, padx=5, sticky=W)

    row += 1

    # force recalibration on all joints check button
    self.m_varForceRecalib = IntVar()
    self.m_varForceRecalib.set(self.m_config['force_recalib'])
    w = Checkbutton(frame,
        text="Force (re)calibration for all joints on calibrate action.",
        variable=self.m_varForceRecalib)
    w.grid(row=row, column=0, padx=20, sticky=W)

    row += 1

    # warn on release check button
    self.m_varWarnRelease = IntVar()
    self.m_varWarnRelease.set(self.m_config['warn_on_release'])
    w = Checkbutton(frame,
        text="Show warning dialog before releasing pan-tilt.",
        variable=self.m_varWarnRelease)
    w.grid(row=row, column=0, padx=5, sticky=W)

    row += 1

    wframe = Frame(frame)
    wframe.grid(row=row, column=0)

    # cancel button
    w = Button(wframe, width=10, text='Cancel', command=self.close)
    w.grid(row=0, column=0, padx=2, pady=5)
    w['anchor']  = CENTER
    self.m_bttnCancel = w

    # save button
    w = Button(wframe, width=10, text='Save', command=self.ok)
    w.grid(row=0, column=1, padx=2, pady=5)
    w['anchor']  = CENTER
    self.m_bttnOk = w

  #
  ## \brief Destroy window callback.
  #
  def ok(self):
    if self.m_varWarnCalib.get():
      self.m_config['warn_on_calib'] = True
    else:
      self.m_config['warn_on_calib'] = False
    if self.m_varForceRecalib.get():
      self.m_config['force_recalib'] = True
    else:
      self.m_config['force_recalib'] = False
    if self.m_varWarnRelease.get():
      self.m_config['warn_on_release'] = True
    else:
      self.m_config['warn_on_release'] = False

    dirname = home + os.path.sep + pantiltUserDirName
    if not os.path.isdir(dirname):
      try:
        os.mkdir(dirname, 0755)
      except OSError, err:
        print "%s: %s" % (dirname, err)
        return
    filename = dirname + os.path.sep + configFileName
    xml = configXml()
    xml.save(filename, self.m_config)
    self.close()

  #
  ## \brief Destroy window callback.
  #
  def close(self):
    self.destroy()


# ------------------------------------------------------------------------------
# Class warnDlg
# ------------------------------------------------------------------------------

class warnDlg(Toplevel):
  #
  ## \brief Constructor.
  ##
  ## \param cnf     Configuration dictionary.
  ## \param kw      Keyword options.
  #
  def __init__(self, master=None, cnf={}, **kw):
    # initialize dialog data
    kw = self.initData(kw)

    Toplevel.__init__(self, master=master, cnf=cnf, **kw)
    self.title(self.m_title)

    # create and show widgets
    self.createWidgets()

    # allows the enter button to fire either button's action
    self.m_bttnCancel.bind('<KeyPress-Return>', func=self.close)

    # center the dialog over parent panel
    if master is not None:
      self.update_idletasks()
      x0 = master.winfo_rootx()
      y0 = master.winfo_rooty()
      xp = x0 + (master.winfo_width() - self.winfo_width()) / 2 - 8
      yp = y0 + (master.winfo_height() - self.winfo_height()) / 2 - 20
      glist = [self.winfo_width(), self.winfo_height(), xp, yp]
      #self.withdraw() # hide the dialog until position and size is set
      self.geometry('{0}x{1}+{2}+{3}'.format(*glist))
      #self.deiconify() # now show

    # allows us to customize what happens when the close button is pressed
    self.protocol("WM_DELETE_WINDOW", self.close)

    #
    # Modal diagle settings.
    #
    # set the focus on dialog window (needed on Windows)
    self.focus_set()

    # make sure events only go to our dialog
    self.grab_set()

    # make sure dialog stays on top of its parent window (if needed)
    self.transient(master)

    # display the window and wait for it to close
    self.wait_window(self)

  #
  ## \brief Initialize class state data.
  ##
  ## \param kw      Keyword options.
  ##
  ## \return Modified keywords sans this specific class.
  ##
  def initData(self, kw):
    self.m_icons          = {}    # must keep loaded icons referenced
    if kw.has_key('title'):
      self.m_title = kw['title']
      del kw['title']
    else:
      self.m_title = "Warning"
    if kw.has_key('image'):
      self.m_icons['image'] = loadIcon(kw['image'])
      del kw['image']
    else:
      self.m_icons['image'] = None
    if kw.has_key('msg'):
      self.m_msg = kw['msg']
      del kw['msg']
    else:
      self.m_msg = "Warn what???"
    self.m_result = False
    return kw

  #
  ## \brief Create gui widgets with supporting data and show.
  #
  def createWidgets(self):
    frame = Frame(self)
    frame.grid(row=0, column=0)

    # warning image 
    w = Label(frame)
    if self.m_icons['image'] is not None:
      w = Label(frame)
      w['image']  = self.m_icons['image']
    w['anchor'] = CENTER
    w.grid(row=0, column=0, rowspan=2, sticky=W+N+S)

    # top heading
    w = Label(frame)
    helv = tkFont.Font(family="Helvetica",size=24,weight="bold")
    w['font']   = helv
    w['text']   = 'Warning'
    w['anchor'] = CENTER
    w.grid(row=0, column=1, sticky=E+W)

    row = 1

    # warning message
    w = Label(frame)
    w['text']   = self.m_msg
    w['anchor'] = W
    w['justify'] = LEFT
    w.grid(row=row, column=1, padx=5, sticky=E+W)

    row += 1

    wframe = Frame(frame)
    wframe.grid(row=row, column=1)

    # cancel button
    w = Button(wframe, width=10, text='Cancel', command=self.close)
    w.grid(row=0, column=0, padx=2, pady=5)
    w['anchor']  = CENTER
    self.m_bttnCancel = w

    # ok button
    w = Button(wframe, width=10, text='Continue', command=self.ok)
    w.grid(row=0, column=1, padx=2, pady=5)
    w['anchor']  = CENTER
    self.m_bttnContinue = w

  #
  ## \brief Destroy window callback.
  #
  def ok(self):
    self.m_result = True
    self.close()

  #
  ## \brief Destroy window callback.
  #
  def close(self):
    self.destroy()


# ------------------------------------------------------------------------------
# Class moveDlg
# ------------------------------------------------------------------------------

class moveDlg(Toplevel):
  #
  ## \brief Constructor.
  ##
  ## \param cnf     Configuration dictionary.
  ## \param kw      Keyword options.
  #
  def __init__(self, master=None, cnf={}, **kw):
    # initialize dialog data
    kw = self.initData(kw)

    Toplevel.__init__(self, master=master, cnf=cnf, **kw)
    self.title(self.m_title)

    # create and show widgets
    self.createWidgets()

    # allows the enter button to fire either button's action
    self.m_bttnCancel.bind('<KeyPress-Return>', func=self.close)

    # center the dialog over parent panel
    if master is not None:
      self.update_idletasks()
      x0 = master.winfo_rootx()
      y0 = master.winfo_rooty()
      xp = x0 + (master.winfo_width() - self.winfo_width()) / 2 - 8
      yp = y0 + (master.winfo_height() - self.winfo_height()) / 2 - 20
      glist = [self.winfo_width(), self.winfo_height(), xp, yp]
      #self.withdraw() # hide the dialog until position and size is set
      self.geometry('{0}x{1}+{2}+{3}'.format(*glist))
      #self.deiconify() # now show

    # allows us to customize what happens when the close button is pressed
    self.protocol("WM_DELETE_WINDOW", self.close)

    #
    # Modal diagle settings.
    #
    # set the focus on dialog window (needed on Windows)
    self.focus_set()

    # make sure events only go to our dialog
    self.grab_set()

    # make sure dialog stays on top of its parent window (if needed)
    self.transient(master)

    # display the window and wait for it to close
    self.wait_window(self)

  #
  ## \brief Initialize class state data.
  ##
  ## \param kw      Keyword options.
  ##
  ## \return Modified keywords sans this specific class.
  ##
  def initData(self, kw):
    self.m_icons          = {}    # must keep loaded icons referenced
    if kw.has_key('title'):
      self.m_title = kw['title']
      del kw['title']
    else:
      self.m_title = "Move Pan-Tilt To..."
    if kw.has_key('image'):
      self.m_icons['image'] = loadIcon(kw['image'])
      del kw['image']
    else:
      self.m_icons['image'] = None
    self.m_result = False
    self.m_trajectory = kw['trajectory']
    self.m_vals = { }
    del kw['trajectory']
    return kw

  #
  ## \brief Create gui widgets with supporting data and show.
  #
  def createWidgets(self):
    frame = Frame(self)
    frame.grid(row=0, column=0)

    # move image 
    w = Label(frame)
    if self.m_icons['image'] is not None:
      w = Label(frame)
      w['image']  = self.m_icons['image']
    w['anchor'] = CENTER
    w.grid(row=0, column=0, rowspan=2, sticky=W+N+S)

    # top heading
    w = Label(frame)
    helv = tkFont.Font(family="Helvetica",size=12,weight="bold")
    w['font']   = helv
    w['text']   = 'Specify Trajectory'
    w['anchor'] = CENTER
    w.grid(row=0, column=1, sticky=E+W)

    width = 12
    padx  = 2
    pady  = 3
    row   = 1

    wframe = Frame(frame)
    wframe.grid(row=row, column=1)

    #
    # Trajectory Table
    #
    row   = 0

    # left column of labels
    for text in [' ', 'Position(deg):', 'Velocity(%max):', 'Group Velocity:']:
      w = Label(wframe, width=width, padx=padx, pady=pady, anchor=W, text=text)
      w.grid(row=row, column=0, sticky=W+S)
      row += 1

    col         = 1
    trajPoint   = self.m_trajectory.points[0]
    startGroupV = 0.0

    i = 0
    for name in self.m_trajectory.joint_names:
      # joint label
      row = 0
      w = Label(wframe, width=width, padx=padx, pady=pady, anchor=W, text=name)
      w.grid(row=row, column=col, sticky=W)
      self.m_vals[name] = { }

      # joint position
      row += 1
      var = DoubleVar()
      var.set(round10th(radToDeg(trajPoint.positions[i])))
      w = Spinbox(wframe, justify=RIGHT, textvar=var,
                        increment=0.1, from_=-720.0, to=720.0,
                        fg=fgColors['normal'])
      w['width'] = 7
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_vals[name]['position'] = d
    
      # joint velocity
      row += 1
      var = DoubleVar()
      var.set(round10th(trajPoint.velocities[i]))
      startGroupV = var.get()
      w = Spinbox(wframe, justify=RIGHT, textvar=var,
                        increment=0.1, from_=0.0, to=100.0,
                        fg=fgColors['normal'])
      w['width'] = 7
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_vals[name]['velocity'] = d
    
      col += 1
      i += 1

    if i > 0:
      self.update_idletasks()
      name = self.m_trajectory.joint_names[0]
      x0 = self.m_vals[name]['position']['w'].winfo_rootx()
      name = self.m_trajectory.joint_names[i-1]
      x1 = self.m_vals[name]['position']['w'].winfo_rootx() + \
           self.m_vals[name]['position']['w'].winfo_width()
      length = x1 - x0
    else:
      length = 100

    # delta group velocity
    self.m_varGroupVel = DoubleVar()
    self.m_varGroupVel.set(round10th(startGroupV))
    w = Scale(wframe, variable=self.m_varGroupVel,
                        from_=0.0, to=100.0, resolution=1.0,
                        orient=HORIZONTAL, command=self.setGroupV)
    w['width']  = 10
    w['length'] = length
    w.grid(row=3, column=1, columnspan=i, padx=1, pady=0, sticky=W)

    #
    # Dialog Buttons
    #
    row = 2

    wframe = Frame(frame)
    wframe.grid(row=row, column=1)

    # cancel button
    w = Button(wframe, width=10, text='Cancel', command=self.close)
    w.grid(row=0, column=0, padx=2, pady=5)
    w['anchor']  = CENTER
    self.m_bttnCancel = w

    # ok button
    w = Button(wframe, width=10, text='Move', command=self.ok)
    w.grid(row=0, column=1, padx=2, pady=5)
    w['anchor']  = CENTER
    self.m_bttnContinue = w

  #
  ## \brief Delta velocity callback
  #
  def setGroupV(self, v):
    vel = self.m_varGroupVel.get()
    for name in self.m_vals:
      self.m_vals[name]['velocity']['var'].set(vel)

  #
  ## \brief Destroy window callback.
  #
  def ok(self):
    i = 0
    trajPoint = self.m_trajectory.points[0]
    for name in self.m_trajectory.joint_names:
      pos = self.m_vals[name]['position']['var'].get()
      vel = self.m_vals[name]['velocity']['var'].get()
      if vel < 0.0:
        vel = 0.0
      elif vel > 100.0:
        vel = 100.0
      trajPoint.positions[i]  = degToRad(pos)
      trajPoint.velocities[i] = vel
      i += 1
    self.m_result = True
    self.close()

  #
  ## \brief Destroy window callback.
  #
  def close(self):
    self.destroy()



# ------------------------------------------------------------------------------
# Class window
# ------------------------------------------------------------------------------

##
## \brief Window class supporting application.
##
class window(Frame):
  #
  ## \brief Constructor.
  ##
  ## \param master  Window parent master widget.
  ## \param cnf     Configuration dictionary.
  ## \param kw      Keyword options.
  #
  def __init__(self, master=None, cnf={}, **kw):
    # intialize window data
    kw = self.initData(kw)

    Frame.__init__(self, master=master, cnf=cnf, **kw)
    self.master.title("Pan-Tilt Control Panel")
    self.grid(row=0, column=0, padx=5, pady=5)

    # craete and show widgets
    self.createWidgets()

  #
  ## \brief Initialize class state data.
  ##
  ## Any keywords for this application specific window that are not supported 
  ## by the Frame Tkinter class must be removed.
  ##
  ## \param kw      Keyword options.
  ##
  ## \return Modified keywords sans this specific class.
  #
  def initData(self, kw):
    self.m_bHasJointPanel = False # joint state panel [not] created 
                                  # application configuration
    self.m_config         = configDft
    self.m_icons          = {}    # must keep loaded icons referenced
    self.m_wBttn          = {}    # button widgets
    self.m_keysFewMoves   = []    # gui button keys depending on calibration
    self.m_keysNoMoves    = []    # gui button keys depending on robot mode
    self.m_robotStatus    = {}    # robot status widgets, variables, and values
    self.m_robotJoint     = {}    # robot joint state widgets, variables, etc.
    self.m_robotServo     = {}    # master servo to joint name map
                                  # calibration state
    self.m_calibState     = \
      {
        'calibrating':  False,    # [not] calibrating
        'ac':           None,     # calibration action client
        'id':           0         # after id
      }

    if kw.has_key('config'):
      self.m_config = kw['config']
      del kw['config']
    if kw.has_key('pub_joint_move_cb'):
      self.cbMoveRobot = kw['pub_joint_move_cb']
      del kw['pub_joint_move_cb']

    return kw

  #
  ## \brief Create gui widgets with supporting data and show.
  #
  def createWidgets(self):
    self.createHeading()
    self.createLeftButtons()
    self.createCenterPanel()
    self.createRightButtons()
    self.createStatusBar()
    self.updateButtonState(self.m_keysFewMoves, 'disabled')

  #
  ## \brief Create top gui heading.
  #
  def createHeading(self):
    # rn logo
    w = Label(self)
    self.m_icons['rn_logo'] = loadIcon("RNLogo48.png");
    if self.m_icons['rn_logo']:
      w['image'] = self.m_icons['rn_logo']
    else:
      w['text'] = 'rn'
      w['anchor'] = W
      w['width'] = 5
    w.grid(row=0, column=0, sticky=W)
    
    # top heading
    w = Label(self)
    w['font']   = ('Helvetica', 16)
    w['text']   = 'Pan-Tilt'
    w['anchor'] = CENTER
    w.grid(row=0, column=1, sticky=E+W)

    # pantilt logo
    w = Label(self)
    self.m_icons['pan_tilt_logo'] = loadIcon("icons/icon_pan_tilt_logo.png");
    if self.m_icons['pan_tilt_logo']:
      w['image'] = self.m_icons['pan_tilt_logo']
      w['anchor'] = E
    else:
      w['text'] = 'pantilt'
      w['anchor'] = E
      w['width'] = 5
    w.grid(row=0, column=2, sticky=E)
    
  #
  ## \brief Create gui left hand side buttons.
  #
  def createLeftButtons(self):
    wframe = Frame(self)
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=1, column=0, padx=1, pady=3, sticky=N+W+E)

    # calibrate
    w = self.createButton(wframe, "Calibrate", "icons/icon_calib.png",
                            self.calibrate)
    w.grid(row=0, column=0, sticky=N+E+W)
    self.m_icons['calibrate_cancel'] = loadIcon("icons/icon_calib_cancel.png")
    self.m_keysNoMoves.append('calibrate')

    # zero point
    w = self.createButton(wframe, "Zero\nPoint",
        "icons/icon_pan_tilt_zeropt.png",
                            self.gotoZeroPt)
    w.grid(row=3, column=0, sticky=N+E+W)
    self.m_keysFewMoves.append('zero_point')
    self.m_keysNoMoves.append('zero_point')

    # specify move
    w = self.createButton(wframe, "Specify\nMove",
                                  "icons/icon_pan_tilt_in_motion.png",
                                  self.specifyMove)
    w.grid(row=6, column=0, sticky=N+E+W)
    self.m_keysFewMoves.append('specify_move')
    self.m_keysNoMoves.append('specify_move')

  #
  ## \brief Create robot status and joint state center panel.
  #
  def createCenterPanel(self):
    self.m_wPanelFrame = Frame(self)
    self.m_wPanelFrame['borderwidth'] = 2
    self.m_wPanelFrame['relief'] = 'ridge'
    self.m_wPanelFrame.grid(row=1, column=1, padx=1, pady=3, sticky=N+W+E)

    self.createRobotStatusPanel(self.m_wPanelFrame)
    self.createJointStatePanelHdr(self.m_wPanelFrame)

  #
  ## \brief Create robot status upper center panel.
  ##
  ## \param parent  Parent widget
  #
  def createRobotStatusPanel(self, parent):
    wframe = LabelFrame(parent, text='Robot Status')
    wframe['font'] =('Helvetica', 12)
    wframe['fg'] = fgColors['focus']
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=0, column=0, padx=1, pady=3, sticky=N+W+E)

    width = 18
    row   = 0
    col   = 0

    # robot mode status
    var = StringVar()
    text, color = self.toRobotMode(RobotMode.AUTO)
    var.set("Mode: " + text)
    w = Entry(wframe)
    w['borderwidth'] = 2
    w['relief']   = 'flat'
    w['width']    = width
    w['textvar']  = var
    w['fg']       = color
    w['state']    = 'readonly'
    #w['relief']   = 'groove'
    w.grid(row=row, column=col, padx=0, pady=0, sticky=W+E)
    d = {'val': RobotMode.AUTO, 'var': var, 'w': w}
    self.m_robotStatus['mode'] = d

    col += 1

    # robot calibration status
    var = StringVar()
    text, color = self.toCalib(TriState.FALSE)
    var.set("State: " + text)
    w = Entry(wframe)
    w['borderwidth'] = 2
    w['relief']   = 'flat'
    w['width']    = width
    w['textvar']  = var
    w['fg']       = color
    w['state']    = 'readonly'
    #w['relief']   = 'groove'
    w.grid(row=row, column=col, padx=0, pady=0, sticky=W+E)
    d = {'val': TriState.FALSE, 'var': var, 'w': w}
    self.m_robotStatus['calibration'] = d

    col += 1

    # robot motors status
    var = StringVar()
    text, color = self.toMotorsPowered(TriState.FALSE)
    var.set("Motors: " + text)
    w = Entry(wframe)
    w['borderwidth'] = 2
    w['relief']   = 'flat'
    w['width']    = width
    w['textvar']  = var
    w['fg']       = color
    w['state']    = 'readonly'
    #w['relief']   = 'groove'
    w.grid(row=row, column=col, padx=0, pady=0, sticky=W+E)
    d = {'val': TriState.ON, 'var': var, 'w': w}
    self.m_robotStatus['motors'] = d

    col += 1

    spacer = Label(wframe, text=' ', width=15)
    spacer.grid(row=row, column=col, padx=0, pady=0, sticky=W+E)

    col += 1

    wframe = Frame(wframe)
    wframe['borderwidth'] = 0
    wframe['relief'] = 'flat'
    wframe.grid(row=row, column=col, padx=1, pady=3, sticky=N+E)

    self.m_icons['led_dark']  = loadIcon("icons/icon_led_dark_16.png")
    self.m_icons['led_green'] = loadIcon("icons/icon_led_green_16.png")
    self.m_icons['led_red']   = loadIcon("icons/icon_led_red_16.png")

    row = 0
    col = 0

    # moving status
    w = Label(wframe)
    w['text']     = 'Moving'
    w['width']    = width
    w['justify']  = RIGHT
    w['anchor']   = E
    w['relief']   = 'flat'
    w.grid(row=row, column=col, sticky=E+W)
    d = {'val': None, 'var': None, 'w': w}
    self.m_robotStatus['moving_label'] = d

    col += 1

    # moving icon
    w = Label(wframe)
    w['image'] = self.m_icons['led_dark']
    w['justify'] = LEFT
    w.grid(row=row, column=col, sticky=W+E)
    d = {'val': TriState.OFF, 'var': None, 'w': w}
    self.m_robotStatus['moving_led'] = d

    col += 1

    # robot alarms status
    w = Label(wframe)
    w['text']     = 'Alarms'
    w['width']    = width
    w['justify']  = RIGHT
    w['anchor']   = E
    w['relief']   = 'flat'
    w.grid(row=row, column=col, sticky=E+W)
    d = {'val': None, 'var': None, 'w': w}
    self.m_robotStatus['alarms_label'] = d

    col += 1

    # alarms icon
    w = Label(wframe)
    w['image'] = self.m_icons['led_dark']
    w['justify'] = LEFT
    w.grid(row=row, column=col, sticky=W+E)
    d = {'val': TriState.OFF, 'var': None, 'w': w}
    self.m_robotStatus['alarms_led'] = d

    col += 1

    # robot estop status
    w = Label(wframe)
    w['text']     = 'EStop'
    w['width']    = width
    w['justify']  = RIGHT
    w['anchor']   = E
    w['relief']   = 'flat'
    w.grid(row=row, column=col, sticky=E)
    d = {'val': None, 'var': None, 'w': w}
    self.m_robotStatus['estop_label'] = d

    col += 1

    # estop icon
    w = Label(wframe)
    w['image'] = self.m_icons['led_dark']
    w['justify'] = LEFT
    w.grid(row=row, column=col, sticky=E)
    d = {'val': TriState.OFF, 'var': None, 'w': w}
    self.m_robotStatus['estop_led'] = d

  #
  ## \brief Adjust status panel fields to fill width of joint state panel
  ##
  ## \param totWidth  Total text width of joint state panel
  #
  def adjustWidthRobotStatusPanel(self, totWidth):
    width = (totWidth - 12) / 9
    self.m_robotStatus['mode']['w']['width'] = 2 * width
    self.m_robotStatus['calibration']['w']['width'] = 2 * width
    self.m_robotStatus['motors']['w']['width'] = 2 * width
    self.m_robotStatus['moving_label']['w']['width'] = width
    self.m_robotStatus['alarms_label']['w']['width'] = width
    self.m_robotStatus['estop_label']['w']['width'] = width

  #
  ## \brief Create joint state lower center panel headers.
  ##
  ## \param parent  Parent widget
  #
  def createJointStatePanelHdr(self, parent):
    wframe = LabelFrame(parent, text='Joint State')
    wframe['font'] =('Helvetica', 12)
    wframe['fg'] = fgColors['focus']
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=1, column=0, padx=1, pady=3, sticky=N+W+E)
    self.m_wJointStateFrame = wframe

    helv  = tkFont.Font(family="Helvetica",size=10,weight="bold")
    width = 12
    padx  = 2
    pady  = 0
    row   = 0
    col   = 0

    # top rows of labels
    for text in ['', '', '',
        ' Position  ',
        ' Odometer  ',
        '  Encoder  ',
        ' Velocity  ',
        '   Speed   ',
        '   Effort  ',
        'Temperature',
        '  Voltage  ',
        '']:
      w = Label(wframe, width=width, padx=padx, pady=pady, anchor=W,
          font=helv, text=text)
      w.grid(row=row, column=col, sticky=W)
      col += 1

    helv = tkFont.Font(family="Helvetica",size=10,weight="bold",underline=True)
    row  = 1
    col  = 0

    # second rows of labels or units
    for text in [
        '   Joint   ',
        ' Servo Id  ',
        '   State   ',
        ' (degrees) ',
        '  (ticks)  ',
        '  (ticks)  ',
        '(% of max) ',
        '   (raw)   ',
        '   (raw)   ',
        '    (C)    ',
        '  (volts)  ',
        '  Alarms   ']:
      w = Label(wframe, width=width, padx=padx, pady=pady, anchor=W,
          font=helv, text=text)
      w.grid(row=row, column=col, sticky=W)
      col += 1


  #
  ## \brief Create joint state lower center panel state.
  ##
  ## \param joint   Joint state
  #
  def createJointStatePanel(self, joint):
    wframe = self.m_wJointStateFrame

    width = 12

    for i in range(0, len(joint.name)):
      name = joint.name[i]
      self.m_robotJoint[name] = {}

      row = 3 + i;
      col = 0

      # joint
      w = Label(wframe, anchor=W, text=name)
      w['width'] = width
      w.grid(row=row, column=col, sticky=W)

      # master servo id
      col += 1
      var = IntVar()
      var.set(ord(joint.master_servo_id[i]))
      w = Entry(wframe, relief='flat', justify=LEFT, textvar=var,
                        fg=fgColors['normal'], state='readonly')
      w['width'] = width
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_robotJoint[name]['servo_id'] = d
      self.m_robotServo[ord(joint.master_servo_id[i])] = name
    
      # joint state
      col += 1
      var = StringVar()
      w = Entry(wframe, relief='flat', justify=LEFT, textvar=var,
                        fg=fgColors['normal'], state='readonly')
      w['width'] = width
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_robotJoint[name]['state'] = d
    
      # position
      col += 1
      var = DoubleVar()
      var.set(0.0)
      w = Entry(wframe, relief='flat', justify=LEFT, textvar=var,
                        fg=fgColors['normal'], state='readonly')
      w['width'] = width
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_robotJoint[name]['position'] = d
    
      # odometer
      col += 1
      var = IntVar()
      var.set(0)
      w = Entry(wframe, relief='flat', justify=LEFT, textvar=var,
                        fg=fgColors['normal'], state='readonly')
      w['width'] = width
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_robotJoint[name]['odometer'] = d
    
      # encoder
      col += 1
      var = IntVar()
      var.set(0)
      w = Entry(wframe, relief='flat', justify=LEFT, textvar=var,
                        fg=fgColors['normal'], state='readonly')
      w['width'] = width
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_robotJoint[name]['encoder'] = d
    
      # velocity
      col += 1
      var = DoubleVar()
      var.set(0.0)
      w = Entry(wframe, relief='flat', justify=LEFT, textvar=var,
                        fg=fgColors['normal'], state='readonly')
      w['width'] = width
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_robotJoint[name]['velocity'] = d
    
      # raw speed
      col += 1
      var = IntVar()
      var.set(0)
      w = Entry(wframe, relief='flat', justify=LEFT, textvar=var,
                        fg=fgColors['normal'], state='readonly')
      w['width'] = width
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_robotJoint[name]['speed'] = d
    
      # raw effort
      col += 1
      var = IntVar()
      var.set(0)
      w = Entry(wframe, relief='flat', justify=LEFT, textvar=var,
                        fg=fgColors['normal'], state='readonly')
      w['width'] = width
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_robotJoint[name]['effort'] = d
    
      # temperature
      col += 1
      var = IntVar()
      var.set(0)
      w = Entry(wframe, relief='flat', justify=LEFT, textvar=var,
                        fg=fgColors['normal'], state='readonly')
      w['width'] = width
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_robotJoint[name]['temperature'] = d
    
      # voltage
      col += 1
      var = DoubleVar()
      var.set(0.0)
      w = Entry(wframe, relief='flat', justify=LEFT, textvar=var,
                        fg=fgColors['normal'], state='readonly')
      w['width'] = width
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_robotJoint[name]['voltage'] = d
    
      # alarms
      col += 1
      var = StringVar()
      var.set("ok")
      w = Entry(wframe, relief='flat', justify=LEFT, textvar=var,
                            fg=fgColors['ok'], state='readonly')
      w['width'] = width
      w.grid(row=row, column=col, padx=1, pady=0, sticky=W)
      d = {'var': var, 'w': w}
      self.m_robotJoint[name]['alarms'] = d

      self.update_idletasks()

    self.m_bHasJointPanel = True
    
  #
  ## \brief Create gui right hand side buttons.
  #
  def createRightButtons(self):
    wframe = Frame(self)
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=1, column=2, padx=1, pady=3, sticky=N+W+E)

    # estop
    w = self.createButton(wframe, "ESTOP", "icons/icon_estop.png", self.estop,
                                  fg='red')
    w.grid(row=0, column=0, sticky=N+E+W)
    self.m_icons['estop_reset'] = loadIcon("icons/icon_estop_reset.png")

    # freeze
    w = self.createButton(wframe, "Freeze",
                                  "icons/icon_pause.png", self.freeze)
    w.grid(row=1, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('freeze')

    # release
    w = self.createButton(wframe, "Release",
                                  "icons/icon_stop.png", self.release)
    w.grid(row=2, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('release')

    # clear alarms
    w = self.createButton(wframe, "Clear\nAlarms",
                                  "icons/icon_alarm.png", self.clearAlarms)
    w.grid(row=3, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('clear_alarms')

    # settings
    w = self.createButton(wframe, "Settings",
                                  "icons/icon_settings.png", self.settings)
    w.grid(row=4, column=0, sticky=N+E+W)

    # info
    w = self.createButton(wframe, "About",
                                  "icons/icon_info.png", self.about)
    w.grid(row=5, column=0, sticky=N+E+W)

    # quit
    w = self.createButton(wframe, "Quit", "icons/icon_exit.png", self.destroy,
                                  fg='red')
    w.grid(row=6, column=0, sticky=N+E+W)

  #
  ## \brief Create gui status bar at bottom of gui window.
  #
  def createStatusBar(self):
    wframe = Frame(self)
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=2, column=0, columnspan=3, padx=1, pady=3, sticky=N+E+W+S)

    self.m_varStatus = StringVar()
    self.m_varStatus.set("Calibration required.")
    self.m_wStatusBar = Entry(wframe)
    self.m_wStatusBar['width']    = wframe['width']
    self.m_wStatusBar['relief']   = 'flat'
    self.m_wStatusBar['textvar']  = self.m_varStatus
    self.m_wStatusBar['fg']       = fgColors['normal']
    self.m_wStatusBar['state']    = 'readonly'
    self.m_wStatusBar.grid(row=0, column=0, padx=3, pady=3, sticky=N+E+W+S)

  #
  ## \brief Update button activation states.
  #
  def updateButtonState(self, keys, state):
    for key in keys:
      self.m_wBttn[key]['state'] = state

  #
  ## \brief Create button.
  ##
  ## \param parent    Parent widget.
  ## \param text      Button text.
  ## \param imagefile Image file name. None for no image.
  ## \param command   Callback for button push.
  ## \param fg        Foreground text color.
  ##
  ## \return Button widget.
  #
  def createButton(self, parent, text, imagefile, command, fg='black'):
    key = str.lower(text.replace("\n", "_"))
    self.m_icons[key] = loadIcon(imagefile)
    w = Button(parent)
    w['text']     = text
    if self.m_icons[key]:
      w['image']    = self.m_icons[key]
      w['compound'] = LEFT
      w['padx']     = 0
      w['pady']     = 0
      w['anchor']   = W
      w['width']    = 105
    else:
      w['anchor']   = CENTER
      w['width']    = 10
    w['fg']       = fg
    w['command']  = command
    self.m_wBttn[key] = w
    return self.m_wBttn[key]

  #
  ## \brief Destroy window callback.
  #
  def destroy(self):
    self.quit()

  #
  ## \brief (Cancel) calibration callback.
  #
  def calibrate(self):
    # not calibrating - so start calibration
    if not self.m_calibState['calibrating']:
      if self.m_config['warn_on_calib']:
        dlg = warnDlg(master=self,
                      image="PanTiltZeroPt128.png",
                      msg="""\
For best calibration, place the pan-tilt near the zero point.
Make sure the workspace is clear of obstructions.""")
        if not dlg.m_result:
          return
      self.m_calibState['calibrating'] = True
      self.m_wBttn['calibrate']['image'] = self.m_icons['calibrate_cancel']
      self.m_wBttn['calibrate']['text'] = "Cancel\nCalibrate"
      self.showInfo("Calibrating pan-tilt.")
      self.update_idletasks()

      # create calibration action client, if not already created
      if self.m_calibState['ac'] is None:
        self.m_calibState['ac'] = ACCalibrate()

      # start calibration
      if not self.m_calibState['ac'].exec_calib(self.calibrate_monitor,
                                  timeout=1,
                                  force_recalib=self.m_config['force_recalib']):
        self.showError("Could not execute calibration. " \
                       "Is the pan_tilt_control node running?")
        self.calibrate_cancel()

      # check for completion
      else:
        self.m_calibState['id'] = self.after(100, self.calibrate_check_for_done)

    # calibrating - so cancel
    else:
      self.calibrate_cancel()
      self.showInfo("Calibration canceled.")
      
  #
  ## \brief Cancel calibration, setting data and widget state accordingly.
  #
  def calibrate_cancel(self):
      self.m_calibState['ac'].cancel()
      self.m_calibState['calibrating'] = False
      self.m_wBttn['calibrate']['image'] = self.m_icons['calibrate']
      self.m_wBttn['calibrate']['text'] = "Calibrate"
      if self.m_calibState['id'] != 0:
        self.m_calibState['id'] = 0
      self.showError("Calibration preempted.")
      self.update_idletasks()

  #
  ## \brief Check if calibration is complete.
  #
  def calibrate_check_for_done(self):
    state = self.m_calibState['ac'].get_action_state()
    if state == GoalStatus.PENDING or \
       state == GoalStatus.ACTIVE or \
       state == GoalStatus.PREEMPTING or \
       state == GoalStatus.RECALLING:
      self.m_calibState['id'] = self.after(100, self.calibrate_check_for_done)
    else:
      self.m_wBttn['calibrate']['image'] = self.m_icons['calibrate']
      self.m_wBttn['calibrate']['text'] = "Calibrate"
      self.m_calibState['calibrating'] = False
      self.m_calibState['id'] = 0
      if self.m_calibState['ac'].get_result().op == OpState.CALIBRATED:
        self.showInfo("Calibration complete.")
      else:
        self.showError("Calibration failed.")
      self.update_idletasks()

  #
  ## \brief monitor the calibration feedback.
  #
  def calibrate_monitor(self, feedback):
    if self.m_bHasJointPanel:
      self.showJointStates(feedback.joint)
  
  #
  ## \brief Go to zero point position callback.
  #
  def gotoZeroPt(self):
    try:
      rospy.wait_for_service("pan_tilt_control/goto_zero", timeout=1)
    except rospy.ROSException, e:
      self.showError('Goto zero point: ' + e.message + '.')
      return
    try:
      goto_zero_pt = rospy.ServiceProxy('pan_tilt_control/goto_zero', 
                                        GotoZeroPt)
      goto_zero_pt()
    except rospy.ServiceException, e:
      self.showError("Goto zero point failed: %s." % (e.message))
      return
    self.showInfo("Zero point.")
  
  #
  ## \brief Specify move callback.
  #
  def specifyMove(self):
    jointTrajectory  = trajectory_msgs.msg.JointTrajectory()
    jointTrajPoint   = trajectory_msgs.msg.JointTrajectoryPoint()  
    jointTrajectory.points.append(jointTrajPoint)
    for name,val in self.m_robotJoint.iteritems(): 
      jointTrajectory.joint_names.append(name)
      pos = self.m_robotJoint[name]['position']['var'].get()
      jointTrajPoint.positions.append(degToRad(pos))
      jointTrajPoint.velocities.append(10.0)
      jointTrajPoint.accelerations.append(0.0)
    dlg = moveDlg(master=self, image='PanTiltInMotion.png',
                                trajectory=jointTrajectory)
    if not dlg.m_result:
      return
    else:
      self.moveRobot(jointTrajectory)
  
  #
  ## \brief Move robot along trajectory
  #
  def moveRobot(self, trajectory):
    try:
      self.m_joint_cmd_pub.publish(trajectory)
      self.showInfo('Move on specified trajectory.')
    except rospy.ROSException, e:
      self.showError('joint_command: ' + e.message + '.')

  #
  ## \brief (Reset) emergency stop callback.
  #
  def estop(self):
    if self.m_robotStatus['estop_led']['val'] == TriState.FALSE:
      self.showResetEStop()
      try:
        rospy.wait_for_service("pan_tilt_control/estop", timeout=1)
      except rospy.ROSException, e:
        self.showError('Emergency stop: ' + e.message + '.')
        self.showEStop()
        return
      try:
        estop = rospy.ServiceProxy('pan_tilt_control/estop', EStop)
        estop()
      except rospy.ServiceException, e:
        self.showError("Emergency stop request failed: %s." % (e.message))
        self.showEStop()
        return
      self.showError("Pan-Tilt emergency stopped.")
    else:
      self.showEStop()
      try:
        rospy.wait_for_service("pan_tilt_control/reset_estop", timeout=1)
      except rospy.ROSException, e:
        self.showError('Reset emergency stop: ' + e.message + '.')
        self.showResetEStop()
        return
      try:
        reset_estop = rospy.ServiceProxy('pan_tilt_control/reset_estop',
                                          ResetEStop)
        reset_estop()
      except rospy.ServiceException, e:
        self.showError("Reset emergency stop request failed: %s." % (e.message))
        self.showResetEStop()
        return
      self.showInfo("Pan-Tilt emergency stop has been reset.")
  
  #
  ## \brief Show estop button.
  #
  def showEStop(self):
    self.m_wBttn['estop']['image'] = self.m_icons['estop']
    self.m_wBttn['estop']['text']   = "ESTOP"
    self.m_wBttn['estop']['fg']     = fgColors['error']
    self.update_idletasks()

  #
  ## \brief Show reset estop button.
  #
  def showResetEStop(self):
    self.m_wBttn['estop']['image']  = self.m_icons['estop_reset']
    self.m_wBttn['estop']['text']   = "Reset\nESTOP"
    self.m_wBttn['estop']['fg']     = fgColors['normal']
    self.update_idletasks()

  #
  ## \brief Freeze pan-tilt callback.
  #
  def freeze(self):
    try:
      rospy.wait_for_service("pan_tilt_control/freeze", timeout=1)
    except rospy.ROSException, e:
      self.showError('Freeze pan-tilt: ' + e.message + '.')
      return
    try:
      freeze = rospy.ServiceProxy('pan_tilt_control/freeze', Freeze)
      freeze()
    except rospy.ServiceException, e:
      self.showError("Freeze pan-tilt request failed: %s." % (e.message))
      return
    self.showInfo("Pan-Tilt has been frozen at current position.")

  #
  ## \brief Release pan-tilt callback.
  #
  def release(self):
    if self.m_config['warn_on_release']:
      dlg = warnDlg(master=self,
                    image="PanTiltFalling.png",
                    msg="""\
The pan-tilt motors will become unpowered.
The pan-tilt may fall if not in a stable position.""")
      if not dlg.m_result:
        return
    try:
      rospy.wait_for_service("pan_tilt_control/release", timeout=1)
    except rospy.ROSException, e:
      self.showError('Release pan-tilt: ' + e.message + '.')
      return
    try:
      release = rospy.ServiceProxy('pan_tilt_control/release', Release)
      release()
    except rospy.ServiceException, e:
      self.showError("Release pan-tilt request failed: %s." % (e.message))
      return
    self.showInfo("Pan-Tilt has been release, all motors are unpowered.")

  #
  ## \brief Clear alarms callback.
  #
  def clearAlarms(self):
    try:
      rospy.wait_for_service("pan_tilt_control/clear_alarms", timeout=1)
    except rospy.ROSException, e:
      self.showError('Clear alarms: ' + e.message + '.')
      return
    try:
      clear_alarms = rospy.ServiceProxy('pan_tilt_control/clear_alarms',
                                          ClearAlarms)
      clear_alarms()
    except rospy.ServiceException, e:
      self.showError("Clear alarms request failed: %s." % (e.message))
      return
    self.showInfo("Alarms cleared.")
  
  #
  ## \brief Open settings dialog callback.
  #
  def settings(self):
    dlg = configDlg(master=self, config=self.m_config)
    self.m_config = dlg.m_config
  
  #
  ## \brief Show about dialog callback.
  #
  def about(self):
    prodInfo = None
    try:
      rospy.wait_for_service("pan_tilt_control/get_product_info", timeout=1)
    except rospy.ROSException, e:
      self.showError('Get product info: ' + e.message + '.')
    else:
      try:
        get_product_info = rospy.ServiceProxy(
                                          'pan_tilt_control/get_product_info',
                                          GetProductInfo)
        rsp = get_product_info()
        prodInfo = rsp.i
      except rospy.ServiceException, e:
        self.showError("Get product info request failed: %s." % (e.message))
    dlg = AboutDlg(master=self, info=prodInfo, app_ver=appVersion)
  
  #
  ## \brief Update robot status.
  ##
  ## \param status  Robot status extended message.
  #
  def updateRobotStatus(self, status):
    self.showRobotStatus(status)

    # first update of joint state required first
    if self.m_bHasJointPanel:
      self.showServoHealth(status.servo_health)

  #
  ## \brief Update joint state.
  ##
  ## \param joint  Joint state extended message.
  #
  def updateJointStates(self, joint):
    # no joints
    if len(joint.name) == 0:
      return

    # first state message, 
    if not self.m_bHasJointPanel:
      self.createJointStatePanel(joint)

    self.showJointStates(joint)

  #
  ## \brief Show robot status.
  ##
  ## \param status  Robot status extended message.
  #
  def showRobotStatus(self, status):
    if status.mode.val == RobotMode.MANUAL or \
      status.e_stopped.val == TriState.TRUE:
      bNoMoves = True
    else:
      bNoMoves = False

    key = 'mode'
    if self.m_robotStatus[key]['val'] != status.mode.val:
      text, fg = self.toRobotMode(status.mode.val)
      self.m_robotStatus[key]['val'] = status.mode.val
      self.showEntry(self.m_robotStatus[key]['w'],
          self.m_robotStatus[key]['var'], "Mode: "+text, fg)
      if bNoMoves:
        state = 'disabled'
      else:
        state = 'normal'
      self.updateButtonState(self.m_keysNoMoves, state)

    key = 'calibration'
    if self.m_robotStatus[key]['val'] != status.is_calibrated.val:
      text, fg = self.toCalib(status.is_calibrated.val)
      self.m_robotStatus[key]['val'] = status.is_calibrated.val
      self.showEntry(self.m_robotStatus[key]['w'],
          self.m_robotStatus[key]['var'], "State: "+text, fg)
      if status.is_calibrated.val == TriState.TRUE:
        state = 'normal'
      else:
        state = 'disabled'
      if not bNoMoves:
        self.updateButtonState(self.m_keysFewMoves, state)

    key = 'motors'
    if self.m_robotStatus[key]['val'] != status.drives_powered.val:
      text, fg = self.toMotorsPowered(status.drives_powered.val)
      self.m_robotStatus[key]['val'] = status.drives_powered.val
      self.showEntry(self.m_robotStatus[key]['w'],
          self.m_robotStatus[key]['var'], "Motors: "+text, fg)

    key = 'moving_led'
    if self.m_robotStatus[key]['val'] != status.in_motion.val:
      self.m_robotStatus[key]['val'] = status.in_motion.val
      if status.in_motion.val == TriState.ON:
        self.m_robotStatus[key]['w']['image'] = self.m_icons['led_green'] 
      else:
        self.m_robotStatus[key]['w']['image'] = self.m_icons['led_dark'] 

    key = 'alarms_led'
    if self.m_robotStatus[key]['val'] != status.in_error.val:
      self.m_robotStatus[key]['val'] = status.in_error.val
      if status.in_error.val == TriState.TRUE:
        self.m_robotStatus[key]['w']['image'] = self.m_icons['led_red'] 
      else:
        self.m_robotStatus[key]['w']['image'] = self.m_icons['led_dark'] 

    key = 'estop_led'
    if self.m_robotStatus[key]['val'] != status.e_stopped.val:
      self.m_robotStatus[key]['val'] = status.e_stopped.val
      if status.e_stopped.val == TriState.TRUE:
        self.m_robotStatus[key]['w']['image'] = self.m_icons['led_red'] 
      else:
        self.m_robotStatus[key]['w']['image'] = self.m_icons['led_dark'] 
      if bNoMoves:
        state = 'disabled'
      else:
        state = 'normal'
      self.updateButtonState(self.m_keysNoMoves, state)

  #
  ## \brief Show joint state.
  ##
  ## \param joint  Joint state extended message.
  #
  def showJointStates(self, joint):
    for i in range(0, len(joint.name)):
      name = joint.name[i]
      if not self.m_robotJoint.has_key(name):
        continue

      key = 'state'
      val, fg = self.toJointState(joint.op_state[i].calib_state)
      if self.m_robotJoint[name][key]['var'].get() != val:
        self.showEntry(self.m_robotJoint[name][key]['w'],
                     self.m_robotJoint[name][key]['var'], val, fg)

      key = 'position'
      val, fg = self.toDeg(joint.position[i])
      if self.m_robotJoint[name][key]['var'].get() != val:
        self.showEntry(self.m_robotJoint[name][key]['w'],
                     self.m_robotJoint[name][key]['var'], val, fg)

      key = 'odometer'
      val = joint.odometer_pos[i]
      if self.m_robotJoint[name][key]['var'].get() != val:
        self.showEntry(self.m_robotJoint[name][key]['w'],
                     self.m_robotJoint[name][key]['var'],
                     val, fgColors['normal'])

      key = 'encoder'
      val = joint.encoder_pos[i]
      if self.m_robotJoint[name][key]['var'].get() != val:
        self.showEntry(self.m_robotJoint[name][key]['w'],
                     self.m_robotJoint[name][key]['var'],
                     val, fgColors['normal'])

      key = 'velocity'
      val, fg = self.toVelocity(joint.velocity[i])
      if self.m_robotJoint[name][key]['var'].get() != val:
        self.showEntry(self.m_robotJoint[name][key]['w'],
                     self.m_robotJoint[name][key]['var'], val, fg)

      key = 'speed'
      val = joint.raw_speed[i]
      if self.m_robotJoint[name][key]['var'].get() != val:
        self.showEntry(self.m_robotJoint[name][key]['w'],
                     self.m_robotJoint[name][key]['var'],
                     val, fgColors['normal'])

      key = 'effort'
      val, fg = self.toEffort(joint.effort[i])
      if self.m_robotJoint[name][key]['var'].get() != val:
        self.showEntry(self.m_robotJoint[name][key]['w'],
                     self.m_robotJoint[name][key]['var'], val, fg)

  #
  ## \brief Show servo health.
  ##
  ## \param health  Servo health message.
  #
  def showServoHealth(self, health):
    for i in range(0, len(health)):
      servo_id = health[i].servo_id
      if not self.m_robotServo.has_key(servo_id):
        continue

      name = self.m_robotServo[servo_id]

      key = 'temperature'
      val = int(health[i].temp)
      if self.m_robotJoint[name][key]['var'].get() != val:
        fg = self.toTemperatureColor(val)
        self.showEntry(self.m_robotJoint[name][key]['w'],
                       self.m_robotJoint[name][key]['var'], val, fg)

      key = 'voltage'
      val = health[i].voltage
      if self.m_robotJoint[name][key]['var'].get() != val:
        volts, fg = self.toVoltage(val)
        self.showEntry(self.m_robotJoint[name][key]['w'],
                       self.m_robotJoint[name][key]['var'], volts, fg)

      key = 'alarms'
      val, fg = self.toAlarms(health[i].alarm)
      if self.m_robotJoint[name][key]['var'].get() != val:
        self.showEntry(self.m_robotJoint[name][key]['w'],
                       self.m_robotJoint[name][key]['var'], val, fg)

  #
  ## \brief Show information message on status bar.
  ##
  ## \param msg   Info message string.
  #
  def showInfo(self, msg):
    self.m_wStatusBar["state"] = "normal"
    self.m_wStatusBar["fg"]    = fgColors['normal']
    self.m_varStatus.set(msg)
    self.m_wStatusBar["state"] = "readonly"

  #
  ## \brief Show error message on status bar.
  ##
  ## \param msg   Error message string.
  #
  def showError(self, msg):
    self.m_wStatusBar["state"] = "normal"
    self.m_wStatusBar["fg"]    = fgColors['error']
    self.m_varStatus.set(msg)
    self.m_wStatusBar["state"] = "readonly"

  #
  ## \brief Show text on read-only entry.
  ##
  ## \param w     Entry widget.
  ## \param var   Bound entry variable.
  ## \param val   Variable value.
  ## \param fg    Text foreground color.
  #
  def showEntry(self, w, var, val, fg='black'):
    w['state'] = 'normal'
    w['fg']    = fg
    var.set(val)
    w['state'] = 'readonly'

  def toRobotMode(self, mode):
    if mode == RobotMode.MANUAL:
      return ("Manual", fgColors['normal'])
    elif mode == RobotMode.AUTO:
      return ("Auto", fgColors['normal'])
    else:
      return (repr(mode), fgColors['error'])

  def toCalib(self, tristate):
    if tristate == TriState.FALSE:
      return ("Not calibrated", fgColors['normal'])
    elif tristate == TriState.TRUE:
      return ("Calibrated", fgColors['normal'])
    else:
      return (repr(tristate), fgColors['error'])

  def toMotorsPowered(self, tristate):
    if tristate == TriState.FALSE:
      return ("Unpowered", fgColors['normal'])
    elif tristate == TriState.TRUE:
      return ("Powered", fgColors['normal'])
    else:
      return (repr(tristate), fgColors['error'])

  def toJointState(self, opstate):
      if opstate == OpState.UNCALIBRATED:
        return ("uncalibrated", fgColors['error'])
      elif opstate == OpState.CALIBRATING:
        return ("calibrating", fgColors['focus'])
      elif opstate == OpState.CALIBRATED:
        return ("calibrated", fgColors['normal'])
      else:
        return (repr(opstate), fgColors['error'])

  def toDeg(self, rad):
    deg = math.degrees(rad)
    return round100th(deg), fgColors['normal']

  def toVelocity(self, percent):
    return round10th(percent), fgColors['normal']

  def toEffort(self, effort):
    absraw = math.fabs(effort)
    raw    = int(effort)
    if absraw < 900:
      return (raw, fgColors['normal'])
    elif absraw < 1000:
      return (raw, fgColors['warning'])
    else:
      return (raw, fgColors['error'])

  def toTemperatureColor(self, temp):
    if temp >= 75:
      return fgColors['error']
    elif temp >= 60:
      return fgColors['warning']
    else:
      return fgColors['normal']

  def toVoltage(self, volts):
    volts = round10th(volts)
    if volts >= 10.5 and volts <= 13.0:
      return (volts, fgColors['normal'])
    elif volts >= 9.5 and volts <= 13.5:
      return (volts, fgColors['warning'])
    else:
      return (volts, fgColors['error'])

  def toAlarms(self, alarms):
    if alarms == ServoHealth.ALARM_NONE:
      return (alarmStrings[ServoHealth.ALARM_NONE], fgColors['ok'])
    text = ""
    sep  = ""
    for bit in alarmStrings.keys():
      if bit & alarms:
        if len(alarmStrings[bit]) > 0:
          text += sep + alarmStrings[bit]
          sep = ','
    return (text, fgColors['error'])


# ------------------------------------------------------------------------------
# Exception Class usage
# ------------------------------------------------------------------------------

##
## \brief Unit test command-line exception class.
##
## Raise usage excpetion.
##
class usage(Exception):

  ##
  ## \brief Constructor.
  ##
  ## \param msg   Error message string.
  ##
  def __init__(self, msg):
    ## error message attribute
    self.msg = msg


# ------------------------------------------------------------------------------
# Class application
# ------------------------------------------------------------------------------

##
## \brief Pan-Tilt control panel.
##
class application():

  #
  ## \brief Constructor.
  #
  def __init__(self):
    self._Argv0 = __file__
    self.m_win = None

  #
  ## \brief Print usage error.
  ##
  ## \param emsg  Error message string.
  #
  def printUsageErr(self, emsg):
    if emsg:
      print "%s: %s" % (self._Argv0, emsg)
    else:
      print "%s: error" % (self._Argv0)
    print "Try '%s --help' for more information." % (self._Argv0)

  ## \brief Print Command-Line Usage Message.
  def printUsage(self):
    print \
"""
usage: %s [OPTIONS] <image_dir>

     %s --help

Options and arguments:

-h, --help                : Display this help and exit.
"""  % (self._Argv0, self._Argv0)
 
  #
  ## \brief Get command-line options
  ##  
  ## \param argv          Argument list. If not None, then overrides
  ##                      command-line arguments.
  ## \param [out] kwargs  Keyword argument list.  
  ##
  ## \return Parsed keyword arguments.
  #
  def getOptions(self, argv=None, **kwargs):
    if argv is None:
      argv = sys.argv

    self._Argv0 = kwargs.get('argv0', __file__)

    # defaults
    kwargs['debug'] = 0

    # parse command-line options
    try:
      opts, args = getopt.getopt(argv[1:], "?h",
          ['help', ''])
    except getopt.error, msg:
      raise usage(msg)
    for opt, optarg in opts:
      if opt in ('-h', '--help', '-?'):
        self.printUsage()
        sys.exit(0)

    #if len(args) < 1:
    #  self.printUsageErr("No input xml file specified")
    #  sys.exit(2)
    #else:
    #  kwargs['filename'] = args[0]

    return kwargs

  #
  ## \brief Initialize interface to pan_tilt_control.
  #
  def initRobot(self):
    self.m_win.showInfo("Initializing interface to pan-tilt.")

    rospy.init_node("pan_tilt_panel")

    # subscribe to extended robot status data
    rospy.Subscriber("pan_tilt_control/robot_status_ex", 
                     RobotStatusExtended, 
                     self.m_win.updateRobotStatus) 

    # subscribe to extended joint state data
    rospy.Subscriber("pan_tilt_control/joint_states_ex", 
                     JointStateExtended, 
                     self.m_win.updateJointStates) 

    # publish trajectory to pan-tilt controller
    self.m_win.m_joint_cmd_pub = rospy.Publisher(
        "pan_tilt_control/joint_command",
        trajectory_msgs.msg.JointTrajectory)

    self.m_win.showInfo("Pan-Tilt interface initialized.")

  #
  ## \brief Run application.
  ##    
  ## \param argv    Optional argument list to override command-line arguments.
  ## \param kwargs  Optional keyword argument list.
  ##
  ## \return Exit code.
  #
  def run(self, argv=None, **kwargs):
  
    # parse command-line options and arguments
    kwargs = self.getOptions(argv, **kwargs)

    # parse application configuration xml file
    filename = home + os.path.sep + pantiltUserDirName + os.path.sep + \
        configFileName
    xml = configXml()
    config = xml.parse(filename)
    del xml

    # create root 
    root = Tk()

    # create application window
    self.m_win = window(master=root, config=config)

    root.protocol('WM_DELETE_WINDOW', root.destroy)

    root.columnconfigure(0, weight=1)
    root.rowconfigure(0, weight=1)

    # initialize robot interface
    self.initRobot()

    # go for it
    self.m_win.mainloop()

    return 0


# ------------------------------------------------------------------------------
# main
# ------------------------------------------------------------------------------
if __name__ == '__main__':
  app = application();
  sys.exit( app.run() );
